name: Debugger
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

jobs:
  debugger:
    runs-on: ${{ matrix.on }}
    strategy:
      fail-fast: false
      matrix:
        on: ["ubuntu-24.04", "macos-13", "macos-14", "macos-15", "macos-15-intel"]
    steps:
      - uses: actions/checkout@v4
        with: { submodules: recursive }
      - uses: prefix-dev/setup-pixi@v0.8.1
        with: { pixi-version: v0.42.1 }
      - uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 3m
          authorized-users: saraedum
